#pragma once
#ifndef _MeshPost2d_LaplacianSmoothingSurface_AvgFun_Header
#define _MeshPost2d_LaplacianSmoothingSurface_AvgFun_Header

#include <MeshPost2d_LaplacianSmoothingSurface_AvgFunFwd.hxx>
#include <MeshPost_LaplacianSmoothing_AvgFun.hxx>

#endif // !_MeshPost2d_LaplacianSmoothingSurface_AvgFun_Header
