#include <HydStatic_HydGphCurves.hxx>

#include <HydStatic_xDraft.hxx>
#include <TnbError.hxx>
#include <OSstream.hxx>

#include <Geom2d_BSplineCurve.hxx>
#include <Geom2dAPI_Interpolate.hxx>
#include <TColgp_HArray1OfPnt2d.hxx>
#include <StdFail_NotDone.hxx>

#include <HydStatic_HydGphCurveM.cxx>

HYDSTATIC_HYDGRAPHCURVE_IMPL(LCF)
HYDSTATIC_HYDGRAPHCURVE_IMPL(LCB)
HYDSTATIC_HYDGRAPHCURVE_IMPL(MCT)
HYDSTATIC_HYDGRAPHCURVE_IMPL(AW)
HYDSTATIC_HYDGRAPHCURVE_IMPL(DISPV)
HYDSTATIC_HYDGRAPHCURVE_IMPL(DISPMFW)
HYDSTATIC_HYDGRAPHCURVE_IMPL(DISPMSW)
HYDSTATIC_HYDGRAPHCURVE_IMPL(KB)
HYDSTATIC_HYDGRAPHCURVE_IMPL(KM)
HYDSTATIC_HYDGRAPHCURVE_IMPL(KML)

HYDSTATIC_HYDGRAPHCURVE_IMPL(CB)
HYDSTATIC_HYDGRAPHCURVE_IMPL(CM)
HYDSTATIC_HYDGRAPHCURVE_IMPL(CP)
HYDSTATIC_HYDGRAPHCURVE_IMPL(CWL)

#undef HYDSTATIC_HYDGRAPHCURVE_IMPL