#pragma once
#ifndef _MeshPost2d_LaplacianSmoothingSurfaceUniMetric_AvgFun_Header
#define _MeshPost2d_LaplacianSmoothingSurfaceUniMetric_AvgFun_Header

#include <MeshPost2d_LaplacianSmoothingSurfaceUniMetric_AvgFunFwd.hxx>
#include <MeshPost_LaplacianSmoothing_AvgFun.hxx>

BOOST_SERIALIZATION_ASSUME_ABSTRACT(tnbLib::MeshPost2d_LaplacianSmoothingSurfaceUniMetric_AvgFun);

#endif // !_MeshPost2d_LaplacianSmoothingSurfaceUniMetric_AvgFun_Header
