#pragma once
#ifndef _MeshPost2d_LaplacianSmoothingSurfaceUniMetric_AvgFun_Header
#define _MeshPost2d_LaplacianSmoothingSurfaceUniMetric_AvgFun_Header

#include <MeshPost2d_LaplacianSmoothingSurfaceUniMetric_AvgFunFwd.hxx>
#include <MeshPost_LaplacianSmoothing_AvgFun.hxx>

#endif // !_MeshPost2d_LaplacianSmoothingSurfaceUniMetric_AvgFun_Header
